### ISSUE TITLE
carton doesn't install configure deps, but checks them

### ISSUE THREAD

**Issue by skaji** [perl-carton/carton#144]
carton (or cpanm) doesn't install configure deps, but checks them.
Here is an example.

```
% cat cpanfile
on configure => sub {
    requires 'Module::CPANfile';
};

% carton install
Installing modules using /Users/skaji/tmp/cpanfile
Complete! Modules were installed into /Users/skaji/tmp/local

% carton check
Following dependencies are not satisfied.
  Module::CPANfile is not installed. Needs 0
Run `carton install` to install them.
```

I'm using carton v1.0.901, cpanm 1.7102.

**Comment by zebardy** [comment]
I'm struggling with this issue right now. Is it reasonable expected behaviour for carton to install configure deps when running "carton install"? If this can be decided to be a bug and correct behaviour would be to install configure dependencies, then I might spend some time having a go at a patch for this. It would be a reasonable investment against the frustrations this issue is causing me.

**Comment by miyagawa** [comment]
>  Is it reasonable expected behaviour for carton to install configure deps when running "carton install"?

I don't think so, because projects using cpanfile can configure dependencies out of cpanfile correctly, without running the configure script. 

what is doing wrong is the `carton check` that warns about configure dependencies.

Personally, carton check command is broken and I would recommend against using it.

**Comment by cxw42** [comment]
I just tripped over this --- carton 1.0.34 doesn't fetch `configure` dependencies when doing `carton bundle`.  I had to list MBT as a runtime dependency as well as as configure dependency, or else the cpanm installation from a bundle died for lack of MBT.
