### ISSUE TITLE
install --deployment should only install runtime dependencies

### ISSUE THREAD

**Issue by bwilliams** [perl-carton/carton#200]
We have the use case #1 from your blog entry about the cpanfile http://weblog.bulknews.net/post/44963580392/what-is-cpanfile-and-why-do-i-want-to-use-it

It was nice in the cpanfile to distinguish runtime requires from other requires like test, but I really need the carton install --deployment to only install my runtime dependencies and only runtime dependencies recursively down the dependency chain.

Please add an option to exclude non runtime depencies on install, to make for safe and easy deployment.

**Comment by miyagawa** [comment]
"non runtime dependencies" includes `develop`, `test`, `configure` and `build`. 

Carton already excludes `develop` and `test` because they're not needed on deployment. They are in fact ignored in development `carton install` run as well.

For `configure` and `build` they're still required, so that you can actually install them via `make install` etc.

**Comment by miyagawa** [comment]
If you mean a **direct** test dependencies in cpanfile, they're still run because there are situations you want to install test dependencies with `carton install --deployment` such as a CI environment (Travis, Jenkins etc.)

If you want to group a list of dependencies only required in some environments, you can use the `feature` group and use `--without=group_name`.

**Comment by bwilliams** [comment]
"carton install --without test --deployment" still installs the test feature for us. We've been using this pattern in Ruby Bundler for some time with "bundle install  --without develpoment test --deployment".

**Comment by miyagawa** [comment]
> "carton install --without test --deployment" still installs the test feature for us.

Right, you have to use some other names with the combination with `feature`, such as:

```perl
feature 'foo' => sub {
  requires 'Foo';
}
```

and run with `--without foo`. 

I'm suggesting this as a workaround.

**Comment by miyagawa** [comment]
This is a valid feature request, and you might want to check out [Carmel](https://github.com/miyagawa/Carmel) which will succeed Carton in the future.
